//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSW.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NSW.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Merge과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_MergeStart {
            get {
                return ResourceManager.GetString("Button_MergeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Split과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_SplitStart {
            get {
                return ResourceManager.GetString("Button_SplitStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Compression과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_StartCompress {
            get {
                return ResourceManager.GetString("Button_StartCompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Decompression과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_StartDecompress {
            get {
                return ResourceManager.GetString("Button_StartDecompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Validate과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Validate {
            get {
                return ResourceManager.GetString("Button_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Game File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Dialog_SelectGameFile {
            get {
                return ResourceManager.GetString("Dialog_SelectGameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No files to compress.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_NoCompressFiles {
            get {
                return ResourceManager.GetString("Error_NoCompressFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No files to decompress.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_NoDecompressFiles {
            get {
                return ResourceManager.GetString("Error_NoDecompressFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No analyzable metadata found.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_NoMetadata {
            get {
                return ResourceManager.GetString("Error_NoMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All Files과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Filter_AllFiles {
            get {
                return ResourceManager.GetString("Filter_AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Switch Files과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Filter_SwitchFiles {
            get {
                return ResourceManager.GetString("Filter_SwitchFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ext과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Header_Ext {
            get {
                return ResourceManager.GetString("Header_Ext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Header_FileName {
            get {
                return ResourceManager.GetString("Header_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Header_FilePath {
            get {
                return ResourceManager.GetString("Header_FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Header_Size {
            get {
                return ResourceManager.GetString("Header_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Header_Type {
            get {
                return ResourceManager.GetString("Header_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Drag &amp; drop files here (NSP, NSZ, XCI, XCZ)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Hint_DragAndDrop {
            get {
                return ResourceManager.GetString("Hint_DragAndDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the output folder.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Hint_SelectOutput {
            get {
                return ResourceManager.GetString("Hint_SelectOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compression과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Compression {
            get {
                return ResourceManager.GetString("Label_Compression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output Path과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_OutputPath {
            get {
                return ResourceManager.GetString("Label_OutputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ━━ Analyzing metadata... ━━과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Log_AnalyzeMetadata {
            get {
                return ResourceManager.GetString("Log_AnalyzeMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{0}] Base not found - skipped과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Log_BaseMissingSkip {
            get {
                return ResourceManager.GetString("Log_BaseMissingSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compressing &amp; Merging...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Log_CompressAndMerge {
            get {
                return ResourceManager.GetString("Log_CompressAndMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compression ratio과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Log_CompressionRatio {
            get {
                return ResourceManager.GetString("Log_CompressionRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Decompressing and merging과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Log_DecompressAndMerge {
            get {
                return ResourceManager.GetString("Log_DecompressAndMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Incomplete file was deleted.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Log_DeleteIncompleteFile {
            get {
                return ResourceManager.GetString("Log_DeleteIncompleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Log_Error {
            get {
                return ResourceManager.GetString("Log_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Final ID: {0} / Version: {1}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Log_FinalId {
            get {
                return ResourceManager.GetString("Log_FinalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Merge completed: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Log_MergeComplete {
            get {
                return ResourceManager.GetString("Log_MergeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{0}] Merge failed: {1}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Log_MergeFailed {
            get {
                return ResourceManager.GetString("Log_MergeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ━━ Starting Super NSP merge ━━과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Log_MergeStart {
            get {
                return ResourceManager.GetString("Log_MergeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Merging...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Log_Merging {
            get {
                return ResourceManager.GetString("Log_Merging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compress과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Log_ModeCompress {
            get {
                return ResourceManager.GetString("Log_ModeCompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Decompress과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Log_ModeDecompress {
            get {
                return ResourceManager.GetString("Log_ModeDecompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error processing과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Log_ProcessError {
            get {
                return ResourceManager.GetString("Log_ProcessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Log_ProcessStart {
            get {
                return ResourceManager.GetString("Log_ProcessStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   split complete: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Log_SplitComplete {
            get {
                return ResourceManager.GetString("Log_SplitComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - {0} Decompressing and splitting...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Log_SplitDecompressing {
            get {
                return ResourceManager.GetString("Log_SplitDecompressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - {0} Splitting...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Log_SplitExtracting {
            get {
                return ResourceManager.GetString("Log_SplitExtracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Split failed (ID: {0}): {1}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Log_SplitFailed {
            get {
                return ResourceManager.GetString("Log_SplitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Already a single content or no items to split.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Log_SplitNoTarget {
            get {
                return ResourceManager.GetString("Log_SplitNoTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} Starting splitting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Log_SplitPreparing {
            get {
                return ResourceManager.GetString("Log_SplitPreparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Separating...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Log_Splitting {
            get {
                return ResourceManager.GetString("Log_Splitting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compressing...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Log_StatusCompressing {
            get {
                return ResourceManager.GetString("Log_StatusCompressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copying...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Log_StatusCopying {
            get {
                return ResourceManager.GetString("Log_StatusCopying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Decompressing...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Log_StatusDecompressing {
            get {
                return ResourceManager.GetString("Log_StatusDecompressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Done과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Log_StatusDone {
            get {
                return ResourceManager.GetString("Log_StatusDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Validating...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Log_StatusValidating {
            get {
                return ResourceManager.GetString("Log_StatusValidating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} title groups detected과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Log_TitleGroupDetected {
            get {
                return ResourceManager.GetString("Log_TitleGroupDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Validating...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Log_Validating {
            get {
                return ResourceManager.GetString("Log_Validating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Validation complete과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Log_ValidationComplete {
            get {
                return ResourceManager.GetString("Log_ValidationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Validation starting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Log_ValidationStart {
            get {
                return ResourceManager.GetString("Log_ValidationStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to write NSP: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Log_WriteNspFailed {
            get {
                return ResourceManager.GetString("Log_WriteNspFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NSW Compression Tool과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Main_CompressTitle {
            get {
                return ResourceManager.GetString("Main_CompressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please add a file containing the Base game.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Main_Err_NoBase {
            get {
                return ResourceManager.GetString("Main_Err_NoBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please add files and try again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Main_Err_NoFiles {
            get {
                return ResourceManager.GetString("Main_Err_NoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   prod.keys file not found. Please place the key file in the application folder.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Main_Err_NoKeys {
            get {
                return ResourceManager.GetString("Main_Err_NoKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   prod.keys file not found. Please place the key file in the Download folder.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Main_Err_NoKeys_Android {
            get {
                return ResourceManager.GetString("Main_Err_NoKeys_Android", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please set the output folder.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Main_Err_NoOutput {
            get {
                return ResourceManager.GetString("Main_Err_NoOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ✓ All tasks completed. Total time: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Main_Log_AllComplete {
            get {
                return ResourceManager.GetString("Main_Log_AllComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ✓ All split tasks completed! Total time: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Main_Log_AllSplitDone {
            get {
                return ResourceManager.GetString("Main_Log_AllSplitDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} elapsed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Main_Log_Elapsed {
            get {
                return ResourceManager.GetString("Main_Log_Elapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reanalyzing file types...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Main_Log_Recalculating {
            get {
                return ResourceManager.GetString("Main_Log_Recalculating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ━━ Starting Split Analysis: {0} ━━과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Main_Log_SplitStart {
            get {
                return ResourceManager.GetString("Main_Log_SplitStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Done!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Main_Msg_Done {
            get {
                return ResourceManager.GetString("Main_Msg_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Splitting is complete.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Main_Msg_SplitDone {
            get {
                return ResourceManager.GetString("Main_Msg_SplitDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Output Folder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Main_SelectFolder {
            get {
                return ResourceManager.GetString("Main_SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NSW Merge Tool과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Main_Title {
            get {
                return ResourceManager.GetString("Main_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Msg_Title_Error {
            get {
                return ResourceManager.GetString("Msg_Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Information과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Msg_Title_Info {
            get {
                return ResourceManager.GetString("Msg_Title_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirmation과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Msg_Title_Question {
            get {
                return ResourceManager.GetString("Msg_Title_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Msg_Title_Warning {
            get {
                return ResourceManager.GetString("Msg_Title_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Analyzing...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Status_Analyzing {
            get {
                return ResourceManager.GetString("Status_Analyzing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Key과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Status_NoKey {
            get {
                return ResourceManager.GetString("Status_NoKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Processing...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Status_Processing {
            get {
                return ResourceManager.GetString("Status_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToolTip_AddFile {
            get {
                return ResourceManager.GetString("ToolTip_AddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sequential Access (Space Priority)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToolTip_BlocklessMode {
            get {
                return ResourceManager.GetString("ToolTip_BlocklessMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Random Access (Speed Priority)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToolTip_BlockMode {
            get {
                return ResourceManager.GetString("ToolTip_BlockMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Output Folder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToolTip_BrowseOutput {
            get {
                return ResourceManager.GetString("ToolTip_BrowseOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compress to NSZ when checked (merge only)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToolTip_Compress {
            get {
                return ResourceManager.GetString("ToolTip_Compress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   3: Fastest | 9: Balanced | 18: Recommended과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToolTip_CompressLevel {
            get {
                return ResourceManager.GetString("ToolTip_CompressLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Output Folder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToolTip_OpenWorkSpace {
            get {
                return ResourceManager.GetString("ToolTip_OpenWorkSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove All Items과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToolTip_RemoveAll {
            get {
                return ResourceManager.GetString("ToolTip_RemoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove Selected Items과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToolTip_RemoveSelected {
            get {
                return ResourceManager.GetString("ToolTip_RemoveSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Runs an additional validation after compression과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToolTip_ValidateCompress {
            get {
                return ResourceManager.GetString("ToolTip_ValidateCompress", resourceCulture);
            }
        }
    }
}
